# Generated by Django 5.0.2 on 2024-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='signature',
            field=models.CharField(max_length=200, null=True, verbose_name='Signature'),
        ),
    ]
